import type { GenericShotMotion } from "@/lib/video-generation/generic-shot-policy";

export const COMMERCE_TEMPLATE_SLUGS = [
  "commerce-aesthetic-mood",
  "commerce-ugc-testimonial",
  "commerce-demo-first-reveal",
  "commerce-single-feature-proof",
  "commerce-unboxing-transform",
  "commerce-value-proof",
  "commerce-problem-solution",
  "commerce-hard-sell-presenter",
  "commerce-talking-head-review",
  "commerce-podcast-authority",
  "commerce-founder-story",
  "commerce-street-interview",
  "commerce-hook-face-demo",
  "commerce-triple-proof",
  "commerce-creator-reaction",
  "commerce-before-after-match",
  "commerce-360-hero-orbit",
  "commerce-variant-lineup",
  "commerce-whats-in-box",
  "commerce-in-hand-scale",
  "commerce-macro-texture-asmr",
  "commerce-dark-luxury-light",
  "commerce-morning-routine",
  "commerce-pov-immersive",
  "commerce-dual-context",
  "commerce-pet-companion",
  "commerce-home-space-styling",
  "commerce-fashion-lookbook",
  "commerce-beauty-texture",
  "commerce-food-sizzle",
  "commerce-tech-feature-focus",
  "commerce-outdoor-rugged",
  "commerce-travel-pack-flow",
  "commerce-gift-unwrap",
] as const;

export type CommerceTemplateSlug = (typeof COMMERCE_TEMPLATE_SLUGS)[number];

/**
 * 分类只允许取 platform-copy 已注册的标签(两种语言的映射都在 i18n 里),
 * 新增分类必须先在 platform-copy 落标签再进这里。
 */
export const COMMERCE_TEMPLATE_CATEGORIES = [
  "电商带货",
  "电商展示",
  "爆款广告",
  "对比转化",
  "质感特写",
  "奢品",
  "社媒循环",
  "生活方式",
  "家居空间",
  "服饰穿搭",
  "美妆护理",
  "食品饮料",
  "科技数码",
  "工具户外",
  "旅行收纳",
  "包装展示",
  "UGC",
] as const;

export type CommerceTemplateCategory =
  (typeof COMMERCE_TEMPLATE_CATEGORIES)[number];

export type CommerceTemplateRecipe = {
  slug: CommerceTemplateSlug;
  name: string;
  nameZh: string;
  category: CommerceTemplateCategory;
  /// 配方修订版本，缺省为 1。ACTIVE 模板不可原地改，修 beats 必须在这里升版，
  /// seed 会创建新版本行并归档旧 ACTIVE(FK 溯源保留)。
  version?: number;
  summary: string;
  summaryZh: string;
  hook: string;
  proof: string;
  cta: string;
  motion: GenericShotMotion;
  beats: readonly [string, string, string];
  coverImage: string;
  cameraStyle: string;
  humanInteraction: "none" | "controlled";
};

export const COMMERCE_TEMPLATE_RECIPES: readonly CommerceTemplateRecipe[] = [
  {
    slug: "commerce-aesthetic-mood",
    name: "Aesthetic Mood",
    nameZh: "氛围质感种草",
    category: "电商带货",
    summary: "Build desire through material, light, and a clean product hero.",
    summaryZh: "用材质、光线与干净产品英雄镜头建立购买欲。",
    hook: "An arresting texture, silhouette, or lifestyle mood in the first three seconds.",
    proof: "Reveal the exact referenced product through material detail and one stable hero angle.",
    cta: "Finish on an uncluttered product hold that gives the spoken CTA room.",
    motion: "static_product",
    beats: [
      "0-3s HOOK: lead with one premium material or lifestyle mood cue; product identity remains readable.",
      "3-10s PROOF: controlled light travels across the exact referenced surface while the camera makes one gentle push.",
      "10-15s CTA HOLD: clean product hero with strong negative space; no model-rendered text.",
    ],
    coverImage: "/template-previews/commerce-aesthetic-mood.jpg",
    cameraStyle: "slow controlled product dolly, macro-to-medium reveal, stable geometry",
    humanInteraction: "none",
  },
  {
    slug: "commerce-ugc-testimonial",
    name: "UGC Testimonial",
    nameZh: "UGC 真实口碑",
    category: "电商带货",
    summary: "A credible first-person reaction followed by visible product proof.",
    summaryZh: "用可信的第一人称体验衔接可见产品证据。",
    hook: "A direct, conversational problem statement or surprising reaction.",
    proof: "Presenter points to one benefit that is visibly supported by the supplied references.",
    cta: "Close with a natural recommendation, not a fabricated review claim.",
    motion: "presenter_point",
    beats: [
      "0-3s HOOK: presenter delivers a concise lived-experience problem beside the product.",
      "3-10s PROOF: presenter points without blocking or operating unverified mechanics; product stays large and consistent.",
      "10-15s CTA HOLD: honest recommendation energy, then product-forward closing frame.",
    ],
    coverImage: "/template-previews/commerce-ugc-testimonial.jpg",
    cameraStyle: "credible phone-camera UGC, restrained handheld texture, stable product framing",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-demo-first-reveal",
    name: "Demo-First Reveal",
    nameZh: "先演示后揭晓",
    category: "电商带货",
    summary: "Open with a verified use result, then reveal how the product delivers it.",
    summaryZh: "先展示可验证的使用结果，再揭示产品如何实现。",
    hook: "Show the outcome or use context immediately without inventing mechanics.",
    proof: "Demonstrate only a state or action visibly supported by the supplied references.",
    cta: "Return to the intact product and one clear reason to try it.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: start on the strongest visibly supported outcome or in-use state.",
      "3-10s PROOF: match cut to the exact referenced product; use only a reference-supported reveal or keep it static.",
      "10-15s CTA HOLD: product hero and concise spoken benefit, with no extra transformation.",
    ],
    coverImage: "/template-previews/commerce-demo-first-reveal.jpg",
    cameraStyle: "result-first match cut, medium proof framing, stable reveal",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-single-feature-proof",
    name: "Single-Feature Proof",
    nameZh: "单卖点硬证据",
    category: "电商带货",
    summary: "Spend the full ad proving one visible feature instead of listing many.",
    summaryZh: "整条广告只证明一个可见卖点，不堆砌功能清单。",
    hook: "A tight visual question focused on one feature.",
    proof: "Use two reference-consistent angles to prove that feature clearly.",
    cta: "End with the feature resolved into a simple buying reason.",
    motion: "static_product",
    beats: [
      "0-3s HOOK: frame one feature as the visual question; keep product identity immediately clear.",
      "3-10s PROOF: two controlled reference angles show the same feature without redesign or unsupported labels.",
      "10-15s CTA HOLD: stable hero shot connects the proof to one spoken buying reason.",
    ],
    coverImage: "/template-previews/commerce-single-feature-proof.jpg",
    cameraStyle: "controlled macro-to-medium proof, precise focus pull, tripod-stable",
    humanInteraction: "none",
  },
  {
    slug: "commerce-unboxing-transform",
    name: "Unboxing Transform",
    nameZh: "开箱场景转化",
    category: "电商带货",
    summary: "Turn a clean package reveal into an immediate product-use context.",
    summaryZh: "从干净开箱揭晓快速转入真实产品使用场景。",
    hook: "Package or closed-state anticipation, only when supported by references.",
    proof: "Reveal the exact product and cut to a truthful use context.",
    cta: "Close on the complete product, packaging, and spoken next step.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: supported package or closed-state anticipation; hands remain anatomically controlled.",
      "3-10s PROOF: one clean cut reveals the exact referenced product, followed by a truthful use-context angle.",
      "10-15s CTA HOLD: complete product and package remain consistent in a purchase-ready hero frame.",
    ],
    coverImage: "/template-previews/commerce-unboxing-transform.jpg",
    cameraStyle: "top-down package reveal into stable three-quarter product hero",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-value-proof",
    name: "Value Proof",
    nameZh: "价值感证明",
    category: "电商带货",
    summary: "Translate visible construction and utility into a confident value story.",
    summaryZh: "把可见做工与用途转化为可信的价值叙事。",
    hook: "Contrast a common compromise with the referenced product's visible quality.",
    proof: "Show construction, included parts, capacity, or finish only when visible.",
    cta: "Conclude with durable-value language without unsupported price claims.",
    motion: "static_product",
    beats: [
      "0-3s HOOK: visual contrast establishes the costly compromise without showing a fake competitor.",
      "3-10s PROOF: stable camera inspects visible construction, capacity, finish, or included parts from references.",
      "10-15s CTA HOLD: complete product hero supports a durable-value spoken CTA; no invented price.",
    ],
    coverImage: "/template-previews/commerce-value-proof.jpg",
    cameraStyle: "clean studio inspection, measured orbit, high-clarity value proof",
    humanInteraction: "none",
  },
  {
    slug: "commerce-problem-solution",
    name: "Problem / Solution",
    nameZh: "痛点解决方案",
    category: "电商带货",
    summary: "Make the pain legible, show the product as the answer, and hold the result.",
    summaryZh: "先让痛点清晰可感，再让产品作为答案出现并保持结果。",
    hook: "A relatable problem state grounded in the intended use context.",
    proof: "Transition to the product without fabricating a before/after result.",
    cta: "Return to a clear product-and-outcome frame with one next step.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: relatable use-context friction, filmed without a fake competitor or exaggerated failure.",
      "3-10s SOLUTION PROOF: cut to the exact referenced product in the same context; preserve scale and geometry.",
      "10-15s CTA HOLD: resolved context and product stay visible together for the spoken next step.",
    ],
    coverImage: "/template-previews/commerce-problem-solution.jpg",
    cameraStyle: "matched-angle problem/solution cut, stable context continuity",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-hard-sell-presenter",
    name: "Hard-Sell Presenter",
    nameZh: "高转化主持带货",
    category: "电商带货",
    summary: "High-energy direct response with strict product and claim control.",
    summaryZh: "高能直接转化表达，同时严格锁定产品与宣称边界。",
    hook: "Presenter calls out the buyer problem directly in the first beat.",
    proof: "Presenter points to one visible feature or supported use context.",
    cta: "Finish with urgent spoken action while the product owns the frame.",
    motion: "presenter_point",
    beats: [
      "0-3s HOOK: energetic presenter names the buyer problem directly beside the product.",
      "3-10s PROOF: presenter points to one visible feature; never obscures it or invents operation.",
      "10-15s CTA HOLD: presenter clears the center as the exact product fills frame for an urgent spoken action.",
    ],
    coverImage: "/template-previews/commerce-hard-sell-presenter.jpg",
    cameraStyle: "energetic sales gimbal, medium presenter framing, product-dominant close",
    humanInteraction: "controlled",
  },
  /// ——以下 27 个配方为 2026-08-03 扩容批次——
  /// 类型全部复刻自开源同行资源(scrollclaw / UGC-Factory / cliprise 等),
  /// 逐条来源映射见 docs/roadmap/2026-08-03-template-library-expansion.md。
  {
    slug: "commerce-talking-head-review",
    name: "Talking-Head Review",
    nameZh: "口播真人实测",
    category: "UGC",
    summary: "A propped-camera creator delivers a tried-it verdict beside the product.",
    summaryZh: "固定手机机位的真人试用口播，从上手到给出真实结论。",
    hook: "Creator opens mid-thought about the thing they just tried, direct to camera.",
    proof: "Creator gestures to the exact referenced product beside them without blocking it.",
    cta: "An honest verdict lands as the product holds the closing frame.",
    motion: "presenter_point",
    beats: [
      "0-3s HOOK: casual propped-phone framing at eye level; creator starts mid-sentence about the product visible beside them.",
      "3-10s PROOF: creator points to one visible benefit of the exact referenced product; camera holds steady, product stays large.",
      "10-15s CTA HOLD: unpolished honest-verdict energy settles into a stable product-forward closing frame.",
    ],
    coverImage: "/template-previews/commerce-talking-head-review.jpg",
    cameraStyle: "propped-phone selfie framing, eye-level static hold, casual room light",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-podcast-authority",
    name: "Podcast Authority",
    nameZh: "播客对谈背书",
    category: "UGC",
    summary: "Podcast-studio credibility: a guest explains the product mid-conversation.",
    summaryZh: "借播客现场的专家对谈感，把产品价值讲得可信。",
    hook: "Drop into a warm podcast set mid-conversation, microphone and headphones visible.",
    proof: "The guest explains one concrete benefit while the product sits clearly on the studio table.",
    cta: "The take lands and the camera settles on the product.",
    motion: "presenter_point",
    beats: [
      "0-3s HOOK: warm podcast studio with visible microphone and over-ear headphones; the guest is already mid-thought.",
      "3-10s PROOF: steady tripod framing while the guest points beside the exact referenced product on the table; no invented endorsements or ratings.",
      "10-15s CTA HOLD: the conversational take concludes and the product owns a calm final frame.",
    ],
    coverImage: "/template-previews/commerce-podcast-authority.jpg",
    cameraStyle: "steady tripod medium close-up, warm amber studio glow, off-center interview framing",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-founder-story",
    name: "Founder Story",
    nameZh: "创始人自述",
    category: "UGC",
    summary: "A maker explains why the product exists and shows one honest detail.",
    summaryZh: "创始人视角讲述产品为何而做，只展示一个真实细节。",
    hook: "A maker speaks plainly at their workspace about the problem that started it.",
    proof: "They present the exact referenced product and point to the one detail they are proud of.",
    cta: "A sincere invitation to try it while the product holds center frame.",
    motion: "presenter_point",
    beats: [
      "0-3s HOOK: grounded workshop or desk context; the maker speaks plainly about the original problem, product already present.",
      "3-10s PROOF: the maker points to one visible crafted detail of the exact referenced product; hands never obscure it.",
      "10-15s CTA HOLD: a sincere spoken invitation over a stable, complete product hero.",
    ],
    coverImage: "/template-previews/commerce-founder-story.jpg",
    cameraStyle: "grounded medium shot, natural workspace light, minimal camera drift",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-street-interview",
    name: "Street Interview",
    nameZh: "街头随机安利",
    category: "UGC",
    summary: "Man-on-the-street energy: one passerby reacts to the product on camera.",
    summaryZh: "街访即视感，一位路人对着镜头聊真实看法。",
    hook: "Daylight street framing; a single interviewee reacts to an off-camera question.",
    proof: "The interviewee gestures at the exact referenced product held beside them; identity stays readable.",
    cta: "A punchy one-line take, then the product fills the closing frame.",
    motion: "presenter_point",
    beats: [
      "0-3s HOOK: daylight sidewalk framing with one interviewee reacting to an off-camera question; product already in hand.",
      "3-10s PROOF: the interviewee points at the exact referenced product for one concrete reason; cast stays a single locked subject.",
      "10-15s CTA HOLD: a punchy closing line, then a product-forward final frame.",
    ],
    coverImage: "/template-previews/commerce-street-interview.jpg",
    cameraStyle: "handheld street interview framing, natural daylight, single subject lock",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-hook-face-demo",
    name: "Hook-Face Demo",
    nameZh: "情绪钩子快切",
    category: "爆款广告",
    summary: "An emotive face stops the scroll, then a hard cut to hands-on proof.",
    summaryZh: "3 秒情绪特写拦住滑动，硬切到上手演示给出证据。",
    hook: "A tight face close-up with one strong readable emotion, no dialogue.",
    proof: "Hard cut to anatomically correct hands presenting the exact referenced product.",
    cta: "The visible result resolves into a product-forward finish.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: tight face close-up holding one strong emotion with minimal motion and no speech; a blink or widening eyes only.",
      "3-10s PROOF: one hard cut to hands presenting the exact referenced product; only reference-supported handling, one visible benefit.",
      "10-15s CTA HOLD: the settled result frame with the product large, intact, and centered.",
    ],
    coverImage: "/template-previews/commerce-hook-face-demo.jpg",
    cameraStyle: "face close-up into POV hands framing, single hard cut, steady finish",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-triple-proof",
    name: "Triple Proof",
    nameZh: "一点三证",
    category: "爆款广告",
    version: 2,
    summary: "Three quick visible proofs stack up the same buying reason.",
    summaryZh: "三个可见证据快切，合力证明同一个买点。",
    hook: "Open the single buying reason on its strongest angle.",
    proof: "Three crisp reference-consistent angles, each proving the same reason from a new side.",
    cta: "The stacked proof resolves into one clean hero frame.",
    motion: "static_product",
    beats: [
      "0-3s HOOK: the strongest angle opens the one buying reason; product identity immediately readable.",
      "3-10s PROOF: three sequential full-frame angles joined by straight cuts, each a reference-supported view proving the same feature; one single full-bleed shot on screen at any moment — never a grid, tile, collage, split screen, or picture-in-picture; lid, cap, and every part keep their exact referenced shape.",
      "10-15s CTA HOLD: a clean product hero connects the three proofs to one spoken reason.",
    ],
    coverImage: "/template-previews/commerce-triple-proof.jpg",
    cameraStyle: "three-angle quick-cut sequence, tripod-stable framing, decisive rhythm",
    humanInteraction: "none",
  },
  {
    slug: "commerce-creator-reaction",
    name: "Creator Reaction",
    nameZh: "真实反应种草",
    category: "爆款广告",
    summary: "A genuine delight reaction carries the product reveal.",
    summaryZh: "以真实惊喜反应带出产品揭晓，用情绪完成种草。",
    hook: "The creator's anticipation right before the reveal.",
    proof: "The reveal lands and the genuine reaction stays while the exact product becomes the subject.",
    cta: "Delight settles; the product holds the final frame.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: anticipation close-up beside a reference-supported closed or held state; genuine energy, no exaggeration.",
      "3-10s PROOF: one supported reveal lands; the creator's delight reads true while the exact referenced product takes the frame.",
      "10-15s CTA HOLD: the reaction settles and the intact product owns the closing hero.",
    ],
    coverImage: "/template-previews/commerce-creator-reaction.jpg",
    cameraStyle: "reaction close-up into product reveal, restrained handheld, warm light",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-before-after-match",
    name: "Matched Before & After",
    nameZh: "同机位前后对照",
    category: "对比转化",
    version: 2,
    summary: "A locked camera axis proves change with one matched cut.",
    summaryZh: "锁定机位的前后同框对切，用真实状态差讲结果。",
    hook: "Open on the honest before state from the final camera position.",
    proof: "One matched cut to the after state with identical framing and lighting, only when both states are referenced.",
    cta: "Hold the after state with the product clearly present.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: the before state from a fully locked, motionless camera; an empty scene with no people anywhere in the entire video.",
      "3-10s PROOF: exactly one instant hard cut — never a dissolve, crossfade, or ghosting — to the after state; camera position, framing, lighting, and room geometry stay pixel-stable, and the only change between halves is the referenced product's presence or state, both states visibly supported by references.",
      "10-15s CTA HOLD: the after state holds motionless with the exact product present for the spoken close.",
    ],
    coverImage: "/template-previews/commerce-before-after-match.jpg",
    cameraStyle: "locked single axis, matched-cut discipline, identical lighting between states",
    humanInteraction: "none",
  },
  {
    slug: "commerce-360-hero-orbit",
    name: "360 Hero Orbit",
    nameZh: "环绕产品秀",
    category: "电商展示",
    version: 2,
    summary: "One controlled orbit shows every side of an unchanged product.",
    summaryZh: "一次稳定环绕看全产品每一面，细节即卖点。",
    hook: "Open mid-orbit on the most distinctive silhouette angle.",
    proof: "The orbit continues at constant height; geometry, color, and labels stay identical all the way around.",
    cta: "The orbit eases to a stop on the strongest hero angle.",
    motion: "static_product",
    beats: [
      "0-3s HOOK: the camera is already circling the product — background parallax visibly sweeps behind it from the first frame; no zooming in place.",
      "3-10s PROOF: the orbit keeps circling at constant height and speed so the product's front, side, and back faces are each revealed in one continuous move; specular highlights travel across the surface while silhouette and labels stay locked; the camera never stops, never pulls back, never merely zooms.",
      "10-15s CTA HOLD: the orbit eases to a stop on the strongest hero angle for the spoken benefit.",
    ],
    coverImage: "/template-previews/commerce-360-hero-orbit.jpg",
    cameraStyle: "constant-height turntable orbit, controlled speed, clean studio key light",
    humanInteraction: "none",
  },
  {
    slug: "commerce-variant-lineup",
    name: "Variant Lineup",
    nameZh: "多色阵列",
    category: "电商展示",
    summary: "A tidy lineup pans across exactly the variants shown in the references.",
    summaryZh: "参考图里的配色与版本一字排开，选购欲直给。",
    hook: "The lineup reveals itself in one lateral glide.",
    proof: "Only variants visible in the references appear; count and colors stay exact through the pan.",
    cta: "Settle on the primary variant as the hero.",
    motion: "static_product",
    beats: [
      "0-3s HOOK: a lateral glide reveals the variant lineup; only variants visible in the references, no invented colors or sizes.",
      "3-10s PROOF: the pan continues with even spacing; each variant keeps exact color, finish, and label fidelity.",
      "10-15s CTA HOLD: the camera settles on the primary variant as a clean hero with negative space.",
    ],
    coverImage: "/template-previews/commerce-variant-lineup.jpg",
    cameraStyle: "lateral slider glide across a tabletop lineup, even studio light, locked height",
    humanInteraction: "none",
  },
  {
    slug: "commerce-whats-in-box",
    name: "What's In The Box",
    nameZh: "开箱全家福",
    category: "电商展示",
    summary: "A top-down flat lay accounts for everything included, no surprises.",
    summaryZh: "俯拍全家福清点包装内每一件，可见即所得。",
    hook: "A top-down flat lay opens with the product centered among its included items.",
    proof: "The camera glides across each included item exactly as shown in references; nothing added or removed.",
    cta: "Pull back to the complete set in one purchase-ready frame.",
    motion: "static_product",
    beats: [
      "0-3s HOOK: top-down flat lay with the product centered and included items arranged around it, all reference-supported.",
      "3-10s PROOF: a slow glide across each included accessory; counts, colors, and labels match the references exactly.",
      "10-15s CTA HOLD: gentle pull-back to the complete set in one tidy purchase-ready frame.",
    ],
    coverImage: "/template-previews/commerce-whats-in-box.jpg",
    cameraStyle: "top-down flat-lay glide with gentle pull-back, even soft light",
    humanInteraction: "none",
  },
  {
    slug: "commerce-in-hand-scale",
    name: "In-Hand Scale",
    nameZh: "掌上真实比例",
    category: "电商展示",
    summary: "A hand enters to give true scale, then the size story lands.",
    summaryZh: "手入画给出真实比例，尺寸感一眼建立。",
    hook: "Product alone; a hand enters to hold it, instantly setting scale.",
    proof: "An anatomically correct hand keeps proportions honest through one gentle supported turn.",
    cta: "The product returns to a clean solo hero with the size story landed.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: the product alone at true scale; a hand enters and holds it, instantly anchoring real-world size.",
      "3-10s PROOF: one gentle reference-supported turn in hand; proportions and geometry stay exact, fingers never obscure identity.",
      "10-15s CTA HOLD: the hand withdraws and the product closes as a clean solo hero.",
    ],
    coverImage: "/template-previews/commerce-in-hand-scale.jpg",
    cameraStyle: "medium close-up with hand-scale reference, gentle supported turn, neutral light",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-macro-texture-asmr",
    name: "Macro Texture Tour",
    nameZh: "材质微距巡礼",
    category: "质感特写",
    summary: "A macro slider tours the material until quality is self-evident.",
    summaryZh: "微距滑轨巡览材质纹理，质感自己会说话。",
    hook: "Extreme close-up of the most tactile texture in the references.",
    proof: "Slow macro travel across grain, weave, or finish; focus breathes but geometry never drifts.",
    cta: "Pull back to reveal the full product that texture belongs to.",
    motion: "static_product",
    beats: [
      "0-3s HOOK: extreme macro on the signature texture of the referenced product; immediately tactile.",
      "3-10s PROOF: slow slider travel with a controlled focus pull across material grain, weave, or finish; geometry never drifts.",
      "10-15s CTA HOLD: pull back to the complete product hero so the texture connects to the buying reason.",
    ],
    coverImage: "/template-previews/commerce-macro-texture-asmr.jpg",
    cameraStyle: "macro slider travel, shallow focus pull, raking key light",
    humanInteraction: "none",
  },
  {
    slug: "commerce-dark-luxury-light",
    name: "Dark Luxury Light",
    nameZh: "暗调奢品光影",
    category: "奢品",
    version: 2,
    summary: "Low-key light carves the product out of darkness into desire.",
    summaryZh: "暗场定向光雕出轮廓，把质感推向高级。",
    hook: "A rim of light traces the silhouette out of a dark field.",
    proof: "A motivated light sweep reveals material and detail with physically plausible reflections.",
    cta: "The full product resolves under a final elegant key light.",
    motion: "static_product",
    beats: [
      "0-3s HOOK: a rim light traces the exact silhouette out of a dark field; identity reads before anything else; exactly one product instance exists in the entire video.",
      "3-10s PROOF: one motivated light sweep travels across material and detail in a single continuous full-frame shot; reflections behave physically, no fantasy glow.",
      "10-15s CTA HOLD: the same single product resolves under an elegant key light with generous negative space; no second copy ever appears.",
    ],
    coverImage: "/template-previews/commerce-dark-luxury-light.jpg",
    cameraStyle: "low-key studio, motivated light sweep, slow push-in",
    humanInteraction: "none",
  },
  {
    slug: "commerce-morning-routine",
    name: "Morning Ritual",
    nameZh: "晨间仪式感",
    category: "生活方式",
    version: 2,
    summary: "Soft morning light and an easy routine make the product feel lived-in.",
    summaryZh: "晨光生活场景中的自然使用，卖的是那种生活。",
    hook: "Warm window light establishes a calm morning scene the buyer wants.",
    proof: "The product appears inside the routine naturally, in supported states only.",
    cta: "The scene settles with the product present and desirable.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: warm window light over a calm morning scene; aspiration reads before the product speaks.",
      "3-10s PROOF: the exact referenced product — including its package or body as shown in the references — appears clearly inside the routine at least once; only supported states, relaxed and anatomically correct hands.",
      "10-15s CTA HOLD: the settled scene holds with the referenced product visible and forward for an unhurried spoken close.",
    ],
    coverImage: "/template-previews/commerce-morning-routine.jpg",
    cameraStyle: "soft window light, lifestyle medium shots, unhurried push-in",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-pov-immersive",
    name: "POV Immersive",
    nameZh: "第一视角上手",
    category: "生活方式",
    summary: "Faceless POV hands make the viewer the one using it.",
    summaryZh: "无脸第一视角上手，让观众自己代入使用。",
    hook: "POV looking down as hands reach for the product.",
    proof: "Hands present the product in reference-supported ways; framing stays strictly first-person.",
    cta: "The product rests in view; the viewer already owns it mentally.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: first-person view looking down as hands reach in toward the referenced product.",
      "3-10s PROOF: strictly first-person handling in reference-supported ways only; hands stay anatomically correct and never hide identity.",
      "10-15s CTA HOLD: the product comes to rest in the POV frame, close and ready, for the spoken next step.",
    ],
    coverImage: "/template-previews/commerce-pov-immersive.jpg",
    cameraStyle: "first-person POV framing, slight natural handheld, close working distance",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-dual-context",
    name: "Dual Context",
    nameZh: "一物双景",
    category: "生活方式",
    summary: "Two truthful settings prove the same product fits both.",
    summaryZh: "两个真实场景各证一次，同一产品处处合适。",
    hook: "Context one establishes instantly with the product placed.",
    proof: "One clean cut to context two; the product stays identical with correct scale in both.",
    cta: "Return to the stronger context for the closing hero.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: the first truthful context establishes with the referenced product naturally placed.",
      "3-10s PROOF: one clean cut to a second truthful context; identity, color, and scale stay locked across both rooms.",
      "10-15s CTA HOLD: return to the stronger context and hold product plus setting together for the close.",
    ],
    coverImage: "/template-previews/commerce-dual-context.jpg",
    cameraStyle: "matched framing across two contexts, stable cuts, natural light in both",
    humanInteraction: "none",
  },
  {
    slug: "commerce-pet-companion",
    name: "Pet Companion",
    nameZh: "萌宠陪伴时刻",
    category: "生活方式",
    summary: "A calm pet moment shows the product in genuine companionship use.",
    summaryZh: "宠物与产品的真实相处瞬间，情绪价值直给。",
    hook: "A pet's genuine attention on the scene with the product present.",
    proof: "The pet interacts only in visibly plausible ways; the product stays intact and readable.",
    cta: "A warm settled moment with the product clearly the enabler.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: pet-level framing catches genuine animal attention with the referenced product already in scene.",
      "3-10s PROOF: one gentle, physically plausible interaction; the animal stays a single consistent subject and the product stays intact.",
      "10-15s CTA HOLD: the warm moment settles with the product forward as the reason it happened.",
    ],
    coverImage: "/template-previews/commerce-pet-companion.jpg",
    cameraStyle: "low pet-level framing, patient holds, warm home light",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-home-space-styling",
    name: "Home Space Styling",
    nameZh: "家居空间焕新",
    category: "家居空间",
    version: 2,
    summary: "A real room shows the product carrying the space.",
    summaryZh: "真实房间里看产品如何撑起整个空间氛围。",
    hook: "The room reads first; something in it draws the eye.",
    proof: "Move closer: the product in context with scale true to the room and material readable.",
    cta: "The wide settles back; the space now sells the product.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: a single real room establishes wide; the referenced product draws the eye without effects; the room is empty of people and hands for the entire video.",
      "3-10s PROOF: the camera pushes along one axis toward the product in context; scale and geometry stay true, one material close-up with no hands touching anything.",
      "10-15s CTA HOLD: settle back to the wide where room and product sell each other; every prop keeps the exact position it had in the opening frame.",
    ],
    coverImage: "/template-previews/commerce-home-space-styling.jpg",
    cameraStyle: "single-room axis push, wide-to-detail progression, daylight interior",
    humanInteraction: "none",
  },
  {
    slug: "commerce-fashion-lookbook",
    name: "Fashion Lookbook",
    nameZh: "穿搭动线",
    category: "服饰穿搭",
    summary: "Fabric, fit, and movement shown the lookbook way.",
    summaryZh: "面料、版型与动态三步走，穿戴类产品的标准打开方式。",
    hook: "Texture close-up of the fabric or material in motion.",
    proof: "Fit from two flattering angles; drape and silhouette stay true to references.",
    cta: "A styled hero stance closes the look.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: fabric or material texture moves in close-up; weave, grain, and color exactly as referenced.",
      "3-10s PROOF: the piece worn or displayed as the references support, from two flattering angles; drape and silhouette stay true.",
      "10-15s CTA HOLD: a styled hero stance holds so the whole look lands with the spoken close.",
    ],
    coverImage: "/template-previews/commerce-fashion-lookbook.jpg",
    cameraStyle: "lookbook pacing, texture close to three-quarter framing, clean daylight",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-beauty-texture",
    name: "Beauty Texture",
    nameZh: "上妆质地演示",
    category: "美妆护理",
    summary: "Texture macro and a clean application gesture, no promised miracles.",
    summaryZh: "质地微距与真实涂抹演示，只展示质感不许诺效果。",
    hook: "The product's texture in appetizing macro, exactly as visible in references.",
    proof: "One clean supported application gesture with realistic skin; no transformation claims.",
    cta: "Packaging hero with the texture story fresh.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: appetizing macro of the product texture as visible in the references; swatch, cream, or liquid reads true.",
      "3-10s PROOF: one clean reference-supported application gesture; skin and hands stay realistic, no before/after effect is implied.",
      "10-15s CTA HOLD: the packaging closes as hero while the texture impression is still fresh.",
    ],
    coverImage: "/template-previews/commerce-beauty-texture.jpg",
    cameraStyle: "beauty macro to countertop framing, soft diffused key, true skin tones",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-food-sizzle",
    name: "Food Appetite",
    nameZh: "食欲声色",
    category: "食品饮料",
    summary: "Appetite cues from real states: texture, color, and the serve.",
    summaryZh: "用真实的质地、色泽与出品瞬间调动食欲。",
    hook: "The most appetizing visible state opens full-frame.",
    proof: "Move only between supported states with natural color; no fake steam or CGI food physics.",
    cta: "The serve-ready frame holds with packaging identity readable.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: the most appetizing reference-supported state fills the frame with natural saturated color.",
      "3-10s PROOF: unhurried cuts move only between states visible in the references; textures stay physical, no fake steam or CGI pours.",
      "10-15s CTA HOLD: the serve-ready frame holds with the package identity readable beside it.",
    ],
    coverImage: "/template-previews/commerce-food-sizzle.jpg",
    cameraStyle: "food macro and tabletop framing, natural appetizing light, unhurried cuts",
    humanInteraction: "none",
  },
  {
    slug: "commerce-tech-feature-focus",
    name: "Tech Feature Focus",
    nameZh: "数码功能聚焦",
    category: "科技数码",
    version: 2,
    summary: "Industrial design and one defining feature, shown not claimed.",
    summaryZh: "工业设计与一个决定性功能点，只展示不吹参数。",
    hook: "The design detail that makes it recognizable, in crisp close-up.",
    proof: "Two engineered angles prove one feature; any screen reads as abstract glow, never fake UI text.",
    cta: "Full device hero with the feature story landed.",
    motion: "static_product",
    beats: [
      "0-3s HOOK: crisp close-up on the signature design detail that makes the referenced device recognizable; the product rests on clean studio surfaces only — no hands, no people, no mannequins, ear stands, or body-part display props anywhere in the video.",
      "3-10s PROOF: two precise engineered angles prove the one defining feature; any screen stays an abstract glow with no readable invented interface.",
      "10-15s CTA HOLD: the full device holds as hero with controlled reflections for the spoken close.",
    ],
    coverImage: "/template-previews/commerce-tech-feature-focus.jpg",
    cameraStyle: "precision product cinematography, engineered angles, controlled reflections",
    humanInteraction: "none",
  },
  {
    slug: "commerce-outdoor-rugged",
    name: "Outdoor Rugged",
    nameZh: "户外实战场景",
    category: "工具户外",
    summary: "Field conditions prove the build without staged abuse.",
    summaryZh: "真实户外环境展示做工与可靠感，不做摆拍暴力测试。",
    hook: "Outdoor terrain and weathered light set the stakes.",
    proof: "Hands bring the product into honest field use with only supported actions; construction reads close-up.",
    cta: "The product stands ready in the environment for the final call.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: real outdoor terrain establishes with the referenced product present; natural hard light sets the stakes.",
      "3-10s PROOF: hands handle the product in reference-supported field use only; one close-up proves visible construction quality.",
      "10-15s CTA HOLD: the product stands ready in the environment for a confident spoken close.",
    ],
    coverImage: "/template-previews/commerce-outdoor-rugged.jpg",
    cameraStyle: "outdoor handheld texture, terrain-wide to detail progression, natural hard light",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-travel-pack-flow",
    name: "Travel Packing Flow",
    nameZh: "旅行收纳动线",
    category: "旅行收纳",
    version: 2,
    summary: "A tidy packing sequence shows capacity and order at a glance.",
    summaryZh: "一段利落的收纳动线，容量与秩序一目了然。",
    hook: "The packed state teases how much fits.",
    proof: "Hands run one supported open-or-place step; compartments appear only as referenced.",
    cta: "The organized final state closes ready to go.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: the neatly packed state teases capacity; the referenced product reads instantly.",
      "3-10s PROOF: hands perform one reference-supported open or place step; compartments and contents appear only as the references show, and every prop stays generic and unbranded — no third-party device logos, marks, or recognizable brand items.",
      "10-15s CTA HOLD: the organized ready-to-go state holds for a crisp spoken close.",
    ],
    coverImage: "/template-previews/commerce-travel-pack-flow.jpg",
    cameraStyle: "top-down and three-quarter packing framing, tidy motion, bright practical light",
    humanInteraction: "controlled",
  },
  {
    slug: "commerce-gift-unwrap",
    name: "Gift Unwrap Moment",
    nameZh: "礼盒仪式感",
    category: "包装展示",
    summary: "Premium packaging opens into a gift-worthy reveal.",
    summaryZh: "高级感包装缓缓开启，把礼物感拍进画面。",
    hook: "The closed premium package under soft celebratory light.",
    proof: "Hands open it exactly as the packaging supports; the product emerges identical to references.",
    cta: "Product beside its packaging in a gift-ready hero.",
    motion: "reveal_transition",
    beats: [
      "0-3s HOOK: the closed package as referenced, under soft celebratory light; anticipation without effects.",
      "3-10s PROOF: hands open the packaging only as its visible construction supports; the exact product emerges identity-locked.",
      "10-15s CTA HOLD: product and packaging rest together in a gift-ready hero for the spoken close.",
    ],
    coverImage: "/template-previews/commerce-gift-unwrap.jpg",
    cameraStyle: "soft celebratory light, top-down opening into three-quarter hero, gentle pacing",
    humanInteraction: "controlled",
  },
] as const;

const BY_SLUG = new Map(
  COMMERCE_TEMPLATE_RECIPES.map((recipe) => [recipe.slug, recipe]),
);

export function getCommerceTemplateRecipe(
  slug: string,
): CommerceTemplateRecipe | null {
  return BY_SLUG.get(slug as CommerceTemplateSlug) ?? null;
}

export function commerceTemplateSummary(
  slug: string,
  locale: "zh-CN" | "en-US" = "en-US",
): string | null {
  const recipe = getCommerceTemplateRecipe(slug);
  if (!recipe) return null;
  return locale === "zh-CN" ? recipe.summaryZh : recipe.summary;
}

export function commerceTemplateStarterPrompt(
  slug: string,
  locale: "zh-CN" | "en-US" = "en-US",
): string | null {
  const recipe = getCommerceTemplateRecipe(slug);
  if (!recipe) return null;
  if (locale === "zh-CN") {
    return `请制作一条 15 秒「${recipe.nameZh}」电商短视频。核心方向：${recipe.summaryZh} 前 3 秒明确抓住注意力，中段只证明一个参考图可见的卖点，结尾回到完整产品并给出口播行动指引。保持产品外形、颜色、材质和配件一致，不虚构功能、价格或效果，画面不要生成文字。`;
  }
  return `Create a 15-second “${recipe.name}” ecommerce video. Hook: ${recipe.hook} Proof: ${recipe.proof} CTA: ${recipe.cta} Preserve the exact referenced product and do not invent features, pricing, results, or on-screen text.`;
}
