import { Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

export function AiGeneratedLabel({
  className,
  compact = false,
}: {
  className?: string;
  compact?: boolean;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-(--radius-sm) border border-border bg-card/95 px-2 py-1 text-meta font-semibold text-foreground",
        className,
      )}
      aria-label="AI Generated by Aivora"
    >
      <Sparkles className="size-3 text-primary" aria-hidden />
      {compact ? "AI" : "AI Generated · Aivora"}
    </span>
  );
}
